adsabs/ADSImportPipeline

docs/overview.md, pipeline/workers.py, requirements.txt
=> Better creation of bibstem field and facets

lib/SolrUpdater.py, pipeline/workers.py
for error 99: https://github.com/adsabs/ADSimportpipeline/issues/113
=> added logging to aid debugging and changed close statement

README.md
=> #116 document fix for missing Solr bibcodes

run.py
=> use new logging config from pipeline util library

.gitignore, README.md
=> #185 cleaned up readme

aip/app.py, aip/models.py, aip/tasks.py, alembic/versions/c723db9f0aae_add_data_source.py, run.py, tests/test_app.py
data from classic and direct ingest for a given bibcode is not merged
=> #188 delete bibcodes with direct ingest

aip/classic/read_records.py
the directory was previously renamed
=> import library from new location

config.py, requirements.txt
and update to the lastest release of ADSPipelineUtils
=> add forgotten config variables

aip/tasks.py, tests/direct/test_tasks.py
records ingested via direct should also update the local postgres database
=> direct updates local database

run.py
so we can easily run with data from today, yesterday or days in the recent past
=> add command line arg for direct date offset

copy_input_files.sh
classic files cache are ascii files and compress by a factor of 10.
this allows us to delete older files less aggressively
=> compress somewhat recent classic files cache

aip/classic/conversions.py, aip/classic/read_records.py, run.py, tests/classic/test_read_records.py
=> implemented checking of canonical bibcodes in canonicalize_records()

requirements.txt
and specify other requirements for python2
=> use latest adsabs-pyingest

aip/direct/ArXivDirect.py, config.py, run.py
- This only affects arXiv direct ingest
- I cleaned up some commented code and unused config variables
=> Added option to process only new arXiv records (on by default)

aip/classic/solr_adapter.py, tests/classic/test_solr_adapter.py, tests/stubdata/mergerdata.py
it now includes the cananoical bibcode
=> change identifier field

aip/classic/merger.py, aip/classic/read_records.py, aip/classic/solr_adapter.py
This made us miss logs such as:
- ADSExports failed: 1998JMatR..13.2476B (Unbalanced Parentheses in Affiliation field)
- ADSExports failed: 1995SurSc.323..340P (Unknown numeric entity: &tilde;)
They were not send to our logging infrastructure, only to disk.
=> Bugfix: bad logger setup not sending to stdout

aip/classic/solr_adapter.py
modified:   aip/classic/solr_adapter.py
Fixes #279
=> update solr_adapter to add GEO/earth science collection

aip/classic/solr_adapter.py
=> Fix for EaArX publication facet

.github/workflows/python_actions.yml, aip/classic/solr_adapter.py
=> dataset pubtype

aip/classic/solr_adapter.py, tests/classic/test_solr_adapter.py, tests/stubdata/ADSRecords/testbibcode
Default value of `'publisher' : 'Publisher'` is now ignored. 
Note: Made a dummy publisher called `test-Publisher` for testing.
=> updated publisher field to ignore default value
